#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "remapper/app/ui_projection.h"
#include "remapper/hat/hat.h"
#include "remapper/interaction/interaction.h"
#include "remapper/renderer/renderer.h"
typedef struct {unsigned fill_calls;unsigned write_calls;uint16_t fill_y[4];uint16_t fill_height[4];uint16_t fill_color[4];} fake_display_t;
static bool fake_fill(void *context,uint16_t x,uint16_t y,uint16_t width,uint16_t height,uint16_t rgb565){fake_display_t *fake=context;assert(x==0u);assert(width==REMAPPER_RENDERER_WIDTH);if(fake->fill_calls<4u){fake->fill_y[fake->fill_calls]=y;fake->fill_height[fake->fill_calls]=height;fake->fill_color[fake->fill_calls]=rgb565;}fake->fill_calls++;return true;}
static bool fake_write(void *context,uint16_t x,uint16_t y,uint16_t width,uint16_t height,const uint16_t *pixels){fake_display_t *fake=context;assert(x<REMAPPER_RENDERER_WIDTH);assert(y<REMAPPER_RENDERER_HEIGHT);assert(width==REMAPPER_RENDERER_GLYPH_WIDTH);assert(height==REMAPPER_RENDERER_GLYPH_HEIGHT);assert(pixels!=NULL);fake->write_calls++;return true;}
static remapper_interaction_result_t send_event(remapper_interaction_state_t *state,remapper_control_t control,remapper_input_phase_t phase){const remapper_input_event_t event={.control=control,.phase=phase};return remapper_interaction_handle_event(state,event);}
static remapper_interaction_result_t click(remapper_interaction_state_t *state,remapper_control_t control){const remapper_interaction_result_t press=send_event(state,control,REMAPPER_INPUT_PRESS);assert(press.consumed);assert(press.command.kind==REMAPPER_COMMAND_NONE);return send_event(state,control,REMAPPER_INPUT_RELEASE);}
static void assert_text(const remapper_ui_frame_t *frame,uint8_t row,uint8_t column,const char *text){for(size_t i=0u;text[i]!='\0';++i)assert(frame->cells[row][(size_t)column+i].character==text[i]);}
static void test_geometry_and_hat_mapping(void){assert(REMAPPER_RENDERER_TEXT_ROWS==9u);assert(REMAPPER_RENDERER_TEXT_COLS==21u);assert(REMAPPER_RENDERER_TEXT_X+(REMAPPER_RENDERER_TEXT_COLS-1u)*REMAPPER_RENDERER_CHAR_ADVANCE+REMAPPER_RENDERER_GLYPH_WIDTH<=REMAPPER_RENDERER_WIDTH);assert(REMAPPER_RENDERER_TEXT_Y+(REMAPPER_RENDERER_TEXT_ROWS-1u)*REMAPPER_RENDERER_LINE_ADVANCE+REMAPPER_RENDERER_GLYPH_HEIGHT<=REMAPPER_RENDERER_HEIGHT);remapper_hat_control_t control=REMAPPER_HAT_CONTROL_COUNT;assert(remapper_hat_control_for_pin(15u,&control)&&control==REMAPPER_HAT_KEY_A);assert(remapper_hat_control_for_pin(17u,&control)&&control==REMAPPER_HAT_KEY_B);assert(remapper_hat_control_for_pin(19u,&control)&&control==REMAPPER_HAT_KEY_X);assert(remapper_hat_control_for_pin(21u,&control)&&control==REMAPPER_HAT_KEY_Y);assert(remapper_hat_control_for_pin(2u,&control)&&control==REMAPPER_HAT_JOY_UP);assert(remapper_hat_control_for_pin(18u,&control)&&control==REMAPPER_HAT_JOY_DOWN);assert(remapper_hat_control_for_pin(16u,&control)&&control==REMAPPER_HAT_JOY_LEFT);assert(remapper_hat_control_for_pin(20u,&control)&&control==REMAPPER_HAT_JOY_RIGHT);assert(remapper_hat_control_for_pin(3u,&control)&&control==REMAPPER_HAT_JOY_PRESS);assert(!remapper_hat_control_for_pin(99u,&control));}
static void test_learn_press_feedback_and_lock(void){remapper_interaction_state_t state;remapper_interaction_init(&state);remapper_ui_frame_t frame;remapper_ui_project(&state,&frame);assert(frame.learn_background);assert(frame.hint_start_row==REMAPPER_RENDERER_TEXT_ROWS);assert_text(&frame,0u,0u,"LEARN THE KEYS");assert(frame.cells[0][0].tone==REMAPPER_UI_TONE_TITLE);assert(frame.cells[1][0].tone==REMAPPER_UI_TONE_ACTIONABLE);assert(frame.cells[1][3].tone==REMAPPER_UI_TONE_ACTIONABLE);remapper_interaction_result_t result=send_event(&state,REMAPPER_CONTROL_JOY_UP,REMAPPER_INPUT_PRESS);assert(result.visual_changed);assert(state.screen==REMAPPER_UX_SCREEN_LEARN_THE_KEYS);remapper_ui_project(&state,&frame);assert(frame.cells[1][0].tone==REMAPPER_UI_TONE_EMPHASIZED);assert(frame.cells[1][1].tone==REMAPPER_UI_TONE_EMPHASIZED);assert(frame.cells[1][3].tone==REMAPPER_UI_TONE_ACTIONABLE);assert(frame.cells[2][0].tone==REMAPPER_UI_TONE_ACTIONABLE);result=send_event(&state,REMAPPER_CONTROL_JOY_UP,REMAPPER_INPUT_RELEASE);assert(result.visual_changed);assert(state.screen==REMAPPER_UX_SCREEN_LEARN_THE_KEYS);remapper_ui_project(&state,&frame);assert(frame.cells[1][0].tone==REMAPPER_UI_TONE_ACTIONABLE);result=send_event(&state,REMAPPER_CONTROL_KEY_Y,REMAPPER_INPUT_PRESS);assert(!state.locked);remapper_ui_project(&state,&frame);for(size_t i=0u;i<5u;++i)assert(frame.cells[7][i].tone==REMAPPER_UI_TONE_EMPHASIZED);result=send_event(&state,REMAPPER_CONTROL_KEY_Y,REMAPPER_INPUT_RELEASE);assert(result.lock_changed);assert(state.locked);assert(state.screen==REMAPPER_UX_SCREEN_LEARN_THE_KEYS);result=send_event(&state,REMAPPER_CONTROL_KEY_A,REMAPPER_INPUT_PRESS);assert(state.locked);assert(result.command.kind==REMAPPER_COMMAND_NONE);result=send_event(&state,REMAPPER_CONTROL_KEY_A,REMAPPER_INPUT_RELEASE);assert(result.lock_changed);assert(!state.locked);assert(state.screen==REMAPPER_UX_SCREEN_HOME);assert(state.selected_option==0u);assert(result.command.kind==REMAPPER_COMMAND_NONE);}
static void test_standard_regions_selection_and_hint_feedback(void){remapper_interaction_state_t state;remapper_interaction_init(&state);(void)click(&state,REMAPPER_CONTROL_KEY_Y);(void)click(&state,REMAPPER_CONTROL_KEY_A);assert(state.screen==REMAPPER_UX_SCREEN_HOME);remapper_ui_frame_t frame;remapper_ui_project(&state,&frame);assert(!frame.learn_background);assert(frame.hint_start_row==7u);assert_text(&frame,0u,0u,"HOME");assert_text(&frame,1u,0u," STATUS");assert(frame.cells[1][1].tone==REMAPPER_UI_TONE_EMPHASIZED);for(size_t c=0u;c<REMAPPER_RENDERER_TEXT_COLS;++c)assert(frame.cells[6][c].character==' ');const uint16_t boundary=remapper_renderer_separator_boundary_y(&frame);assert(boundary==175u);assert(remapper_renderer_background_rgb565(&frame,5u)==0x0000u);assert(remapper_renderer_background_rgb565(&frame,7u)==0x0801u);const remapper_interaction_result_t press=send_event(&state,REMAPPER_CONTROL_KEY_Y,REMAPPER_INPUT_PRESS);assert(press.visual_changed);remapper_ui_project(&state,&frame);assert(frame.cells[1][1].tone==REMAPPER_UI_TONE_ACTIONABLE);assert_text(&frame,8u,0u,"KEY Y: LOCK");assert(frame.cells[8][0].tone==REMAPPER_UI_TONE_EMPHASIZED);fake_display_t fake={0};const remapper_display_hal_t display={.context=&fake,.fill_rect=fake_fill,.write_rgb565=fake_write};assert(remapper_renderer_render(&display,&frame));assert(fake.fill_calls==2u);assert(fake.fill_y[0]==0u&&fake.fill_height[0]==boundary);assert(fake.fill_y[1]==boundary&&fake.fill_height[1]==REMAPPER_RENDERER_HEIGHT-boundary);assert(fake.fill_color[0]==0x0000u);assert(fake.fill_color[1]==0x0801u);assert(fake.write_calls>0u);}
int main(void){test_geometry_and_hat_mapping();test_learn_press_feedback_and_lock();test_standard_regions_selection_and_hint_feedback();return 0;}
